version: '3'

services:
  web:
    build: docker/nginx
    ports:
      - 8000:80
    platform: linux/amd64
    depends_on:
      - app
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/html/public
    environment:
      TZ: Asia/Tokyo
  app:
    build: docker/php
    depends_on:
      - db
    volumes:
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html
      - ./composer.phar:/usr/local/bin/composer
    environment:
      TZ: Asia/Tokyo
  db:
    build: docker/mysql
    ports:
      - 3306:3306
    platform: linux/amd64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: laradock
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  redis:
    build: docker/redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data/:/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
